# -*- coding: utf-8 -*-
"""type conversion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j2mqRxCNFyFD6w-YjFb-3ohp9QXoOmk1
"""

x="10"
y=int(x)
print(y)

a="25"
b=float(a)
print(b)

c=20
d=str(c)
print(d)

e = [1, 2, 3]
f = tuple(e)
print(f)

i=(3,4,5,6)
j=list(i)
print(j)

